"""empty message

Revision ID: 17e211a0fcca
Revises: 
Create Date: 2020-07-23 20:52:18.899716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17e211a0fcca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('common_cnf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.String(length=1024), nullable=False),
    sa.Column('desc', sa.String(length=1024), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', name='uix_key')
    )
    op.create_index('ix_key', 'common_cnf', ['key', 'created'], unique=False)
    op.create_table('demo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_1', sa.String(length=512), nullable=False),
    sa.Column('field_2', sa.String(length=512), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('field_1'),
    sa.UniqueConstraint('field_2')
    )
    op.create_table('env_cnf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('env', sa.String(length=128), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.String(length=1024), nullable=False),
    sa.Column('desc', sa.String(length=1024), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('env', 'key', name='uix_env_key')
    )
    op.create_index('ix_env_key', 'env_cnf', ['env', 'key', 'created'], unique=False)
    op.create_table('srv_cnf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('env', sa.String(length=128), nullable=False),
    sa.Column('team', sa.String(length=128), nullable=False),
    sa.Column('project', sa.String(length=128), nullable=False),
    sa.Column('run_level', sa.Integer(), nullable=False),
    sa.Column('deploy_type', sa.String(length=128), nullable=False),
    sa.Column('current_host', sa.String(length=128), nullable=True),
    sa.Column('dev_master', sa.String(length=128), nullable=True),
    sa.Column('test_master', sa.String(length=128), nullable=True),
    sa.Column('process_key', sa.String(length=128), nullable=True),
    sa.Column('desc', sa.String(length=1024), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('env', 'team', 'project', name='uix_env_team_project')
    )
    op.create_index('ix_env_team_project', 'srv_cnf', ['env', 'team', 'project', 'created'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_env_team_project', table_name='srv_cnf')
    op.drop_table('srv_cnf')
    op.drop_index('ix_env_key', table_name='env_cnf')
    op.drop_table('env_cnf')
    op.drop_table('demo')
    op.drop_index('ix_key', table_name='common_cnf')
    op.drop_table('common_cnf')
    # ### end Alembic commands ###
