"""empty message

Revision ID: b62d1c35a8e2
Revises: 
Create Date: 2020-08-12 14:48:17.213365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b62d1c35a8e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('common_cnf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False, comment='配置key'),
    sa.Column('value', sa.String(length=1024), nullable=False, comment='配置value'),
    sa.Column('desc', sa.String(length=1024), nullable=True, comment='配置描述'),
    sa.Column('active', sa.Boolean(), nullable=False, comment='是否有效'),
    sa.Column('created', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', name='uix_key')
    )
    op.create_index('ix_key', 'common_cnf', ['key', 'created'], unique=False)
    op.create_table('demo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_1', sa.String(length=512), nullable=False, comment='字段1'),
    sa.Column('field_2', sa.String(length=512), nullable=False, comment='字段2'),
    sa.Column('active', sa.Boolean(), nullable=False, comment='是否有效'),
    sa.Column('created', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('field_1'),
    sa.UniqueConstraint('field_2')
    )
    op.create_table('env_cnf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('env', sa.String(length=128), nullable=False, comment='配置对应环境'),
    sa.Column('key', sa.String(length=128), nullable=False, comment='配置key'),
    sa.Column('value', sa.String(length=1024), nullable=False, comment='配置value'),
    sa.Column('desc', sa.String(length=1024), nullable=True, comment='配置描述'),
    sa.Column('active', sa.Boolean(), nullable=False, comment='是否有效'),
    sa.Column('created', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('env', 'key', name='uix_env_key')
    )
    op.create_index('ix_env_key', 'env_cnf', ['env', 'key', 'created'], unique=False)
    op.create_table('srv_cnf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('env', sa.String(length=128), nullable=False, comment='项目所在环境'),
    sa.Column('team', sa.String(length=128), nullable=False, comment='项目组名称'),
    sa.Column('project', sa.String(length=128), nullable=False, comment='项目名称'),
    sa.Column('run_level', sa.Integer(), nullable=False, comment='项目运行级别'),
    sa.Column('deploy_type', sa.String(length=128), nullable=False, comment='项目部署类型'),
    sa.Column('current_host', sa.String(length=128), nullable=True, comment='当前部署IP地址'),
    sa.Column('dev_master', sa.String(length=128), nullable=True, comment='开发负责人'),
    sa.Column('test_master', sa.String(length=128), nullable=True, comment='测试负责人'),
    sa.Column('process_key', sa.String(length=128), nullable=True, comment='进程关键词'),
    sa.Column('desc', sa.String(length=1024), nullable=True, comment='配置描述'),
    sa.Column('active', sa.Boolean(), nullable=False, comment='是否有效'),
    sa.Column('created', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('env', 'team', 'project', name='uix_env_team_project')
    )
    op.create_index('ix_env_team_project', 'srv_cnf', ['env', 'team', 'project', 'created'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_env_team_project', table_name='srv_cnf')
    op.drop_table('srv_cnf')
    op.drop_index('ix_env_key', table_name='env_cnf')
    op.drop_table('env_cnf')
    op.drop_table('demo')
    op.drop_index('ix_key', table_name='common_cnf')
    op.drop_table('common_cnf')
    # ### end Alembic commands ###
